// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sobel_accel_sobel_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_img_address0,
        in_img_ce0,
        in_img_q0,
        out_img_address0,
        out_img_ce0,
        out_img_we0,
        out_img_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [17:0] in_img_address0;
output   in_img_ce0;
input  [7:0] in_img_q0;
output  [17:0] out_img_address0;
output   out_img_ce0;
output   out_img_we0;
output  [7:0] out_img_d0;

reg ap_idle;
reg in_img_ce0;
reg out_img_ce0;
reg out_img_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_205_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln32_reg_689;
reg   [0:0] icmp_ln32_reg_689_pp0_iter1_reg;
reg   [0:0] icmp_ln32_reg_689_pp0_iter2_reg;
reg   [0:0] icmp_ln32_reg_689_pp0_iter3_reg;
wire   [0:0] cmp5_fu_263_p2;
reg   [0:0] cmp5_reg_693;
reg   [0:0] cmp5_reg_693_pp0_iter1_reg;
wire   [0:0] icmp28_fu_279_p2;
reg   [0:0] icmp28_reg_698;
wire   [17:0] add_ln49_fu_295_p2;
reg   [17:0] add_ln49_reg_703;
reg   [8:0] linebuf_addr_reg_708;
reg   [8:0] linebuf_addr_reg_708_pp0_iter1_reg;
reg   [8:0] linebuf_1_addr_reg_714;
reg   [8:0] linebuf_1_addr_reg_714_pp0_iter1_reg;
wire   [0:0] or_ln62_fu_317_p2;
reg   [0:0] or_ln62_reg_720;
reg   [0:0] or_ln62_reg_720_pp0_iter1_reg;
reg   [0:0] or_ln62_reg_720_pp0_iter2_reg;
reg   [0:0] or_ln62_reg_720_pp0_iter3_reg;
reg   [17:0] out_img_addr_reg_729;
reg   [17:0] out_img_addr_reg_729_pp0_iter2_reg;
reg   [17:0] out_img_addr_reg_729_pp0_iter3_reg;
reg   [17:0] out_img_addr_reg_729_pp0_iter4_reg;
wire   [7:0] pix_2_fu_349_p3;
reg   [7:0] pix_2_reg_734;
reg   [7:0] pix_4_reg_741;
wire   [8:0] sub_ln74_fu_397_p2;
reg   [8:0] sub_ln74_reg_746;
wire   [10:0] sub_ln74_2_fu_436_p2;
reg   [10:0] sub_ln74_2_reg_751;
wire   [9:0] add_ln74_1_fu_450_p2;
reg   [9:0] add_ln74_1_reg_756;
wire   [10:0] add_ln75_fu_474_p2;
reg   [10:0] add_ln75_reg_761;
reg   [3:0] tmp_7_reg_766;
wire   [7:0] trunc_ln85_fu_616_p1;
reg   [7:0] trunc_ln85_reg_771;
wire   [7:0] select_ln85_fu_625_p3;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    linebuf_ce0;
reg    linebuf_we0;
reg    linebuf_ce1;
wire   [7:0] linebuf_q1;
reg    linebuf_1_ce0;
reg    linebuf_1_we0;
wire   [8:0] linebuf_1_address1;
reg    linebuf_1_ce1;
wire   [7:0] linebuf_1_q1;
wire   [7:0] ap_phi_reg_pp0_iter0_storemerge_reg_175;
reg   [7:0] ap_phi_reg_pp0_iter1_storemerge_reg_175;
reg   [7:0] ap_phi_reg_pp0_iter2_storemerge_reg_175;
reg   [7:0] ap_phi_reg_pp0_iter3_storemerge_reg_175;
reg   [7:0] ap_phi_reg_pp0_iter4_storemerge_reg_175;
reg   [7:0] ap_phi_reg_pp0_iter5_storemerge_reg_175;
wire   [63:0] zext_ln34_fu_285_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln49_1_fu_344_p1;
reg   [7:0] gy_1_fu_72;
reg   [7:0] pix_1_fu_76;
reg   [7:0] pix_3_fu_80;
reg   [9:0] c_fu_84;
wire   [9:0] add_ln34_fu_323_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_c_load;
reg   [9:0] r_fu_88;
wire   [9:0] select_ln32_1_fu_243_p3;
reg   [9:0] ap_sig_allocacmp_r_load;
reg   [18:0] indvar_flatten_fu_92;
wire   [18:0] add_ln32_1_fu_211_p2;
reg   [18:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [7:0] p_0_0_04426_fu_96;
wire   [7:0] pix_fu_365_p3;
reg   [7:0] p_0_0_04328_fu_100;
reg   [7:0] p_0_0_05130_fu_104;
wire   [0:0] icmp_ln34_fu_229_p2;
wire   [9:0] add_ln32_fu_223_p2;
wire   [8:0] trunc_ln49_fu_251_p1;
wire   [8:0] tmp_3_fu_269_p4;
wire   [9:0] select_ln32_fu_235_p3;
wire   [17:0] tmp_1_fu_255_p3;
wire   [17:0] zext_ln49_fu_291_p1;
wire   [8:0] tmp_4_fu_301_p4;
wire   [0:0] icmp_ln62_fu_311_p2;
wire   [8:0] zext_ln73_2_fu_389_p1;
wire   [8:0] zext_ln73_3_fu_393_p1;
wire   [8:0] shl_ln74_1_fu_403_p3;
wire   [9:0] zext_ln74_fu_411_p1;
wire   [9:0] sub_ln74_1_fu_415_p2;
wire   [8:0] shl_ln_fu_425_p3;
wire  signed [10:0] sext_ln74_1_fu_421_p1;
wire   [10:0] zext_ln73_fu_381_p1;
wire   [9:0] zext_ln74_1_fu_432_p1;
wire   [9:0] zext_ln73_5_fu_446_p1;
wire   [8:0] zext_ln73_1_fu_385_p1;
wire   [8:0] zext_ln68_fu_442_p1;
wire   [8:0] tmp_fu_456_p2;
wire   [9:0] tmp_2_fu_462_p3;
wire  signed [10:0] sext_ln75_fu_470_p1;
wire  signed [10:0] sext_ln74_fu_509_p1;
wire   [10:0] zext_ln74_2_fu_520_p1;
wire   [10:0] add_ln74_fu_515_p2;
wire   [10:0] gx_fu_523_p2;
wire   [10:0] zext_ln73_4_fu_512_p1;
wire   [10:0] gy_3_fu_533_p2;
wire  signed [10:0] gy_fu_538_p2;
wire   [9:0] empty_fu_529_p1;
wire   [0:0] tmp_5_fu_548_p3;
wire   [9:0] sub_ln79_fu_556_p2;
wire   [9:0] abs_gx_fu_562_p3;
wire  signed [31:0] sext_ln67_fu_544_p1;
wire   [0:0] tmp_6_fu_574_p3;
wire   [10:0] sub_ln80_fu_582_p2;
wire   [10:0] abs_gy_fu_588_p3;
wire  signed [11:0] sext_ln80_fu_596_p1;
wire   [11:0] zext_ln79_fu_570_p1;
wire   [11:0] mag_fu_600_p2;
wire   [0:0] icmp_ln83_fu_620_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_186;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 gy_1_fu_72 = 8'd0;
#0 pix_1_fu_76 = 8'd0;
#0 pix_3_fu_80 = 8'd0;
#0 c_fu_84 = 10'd0;
#0 r_fu_88 = 10'd0;
#0 indvar_flatten_fu_92 = 19'd0;
#0 p_0_0_04426_fu_96 = 8'd0;
#0 p_0_0_04328_fu_100 = 8'd0;
#0 p_0_0_05130_fu_104 = 8'd0;
end

sobel_accel_sobel_filter_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_addr_reg_708_pp0_iter1_reg),
    .ce0(linebuf_ce0),
    .we0(linebuf_we0),
    .d0(pix_2_reg_734),
    .address1(linebuf_addr_reg_708),
    .ce1(linebuf_ce1),
    .q1(linebuf_q1)
);

sobel_accel_sobel_filter_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
linebuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_1_addr_reg_714_pp0_iter1_reg),
    .ce0(linebuf_1_ce0),
    .we0(linebuf_1_we0),
    .d0(in_img_q0),
    .address1(linebuf_1_address1),
    .ce1(linebuf_1_ce1),
    .q1(linebuf_1_q1)
);

sobel_accel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if (((icmp_ln32_fu_205_p2 == 1'd0) & (or_ln62_fu_317_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_175 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_175 <= ap_phi_reg_pp0_iter0_storemerge_reg_175;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if (((or_ln62_reg_720_pp0_iter3_reg == 1'd0) & (icmp_ln32_reg_689_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_storemerge_reg_175 <= select_ln85_fu_625_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_storemerge_reg_175 <= ap_phi_reg_pp0_iter4_storemerge_reg_175;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((icmp_ln32_fu_205_p2 == 1'd0)) begin
            c_fu_84 <= add_ln34_fu_323_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_84 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((icmp_ln32_fu_205_p2 == 1'd0)) begin
            indvar_flatten_fu_92 <= add_ln32_1_fu_211_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_92 <= 19'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((icmp_ln32_fu_205_p2 == 1'd0)) begin
            r_fu_88 <= select_ln32_1_fu_243_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_88 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln49_reg_703 <= add_ln49_fu_295_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp5_reg_693 <= cmp5_fu_263_p2;
        cmp5_reg_693_pp0_iter1_reg <= cmp5_reg_693;
        icmp28_reg_698 <= icmp28_fu_279_p2;
        icmp_ln32_reg_689 <= icmp_ln32_fu_205_p2;
        icmp_ln32_reg_689_pp0_iter1_reg <= icmp_ln32_reg_689;
        linebuf_1_addr_reg_714 <= zext_ln34_fu_285_p1;
        linebuf_1_addr_reg_714_pp0_iter1_reg <= linebuf_1_addr_reg_714;
        linebuf_addr_reg_708 <= zext_ln34_fu_285_p1;
        linebuf_addr_reg_708_pp0_iter1_reg <= linebuf_addr_reg_708;
        or_ln62_reg_720 <= or_ln62_fu_317_p2;
        or_ln62_reg_720_pp0_iter1_reg <= or_ln62_reg_720;
        out_img_addr_reg_729 <= zext_ln49_1_fu_344_p1;
        pix_2_reg_734 <= pix_2_fu_349_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln74_1_reg_756 <= add_ln74_1_fu_450_p2;
        add_ln75_reg_761 <= add_ln75_fu_474_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln32_reg_689_pp0_iter2_reg <= icmp_ln32_reg_689_pp0_iter1_reg;
        icmp_ln32_reg_689_pp0_iter3_reg <= icmp_ln32_reg_689_pp0_iter2_reg;
        or_ln62_reg_720_pp0_iter2_reg <= or_ln62_reg_720_pp0_iter1_reg;
        or_ln62_reg_720_pp0_iter3_reg <= or_ln62_reg_720_pp0_iter2_reg;
        out_img_addr_reg_729_pp0_iter2_reg <= out_img_addr_reg_729;
        out_img_addr_reg_729_pp0_iter3_reg <= out_img_addr_reg_729_pp0_iter2_reg;
        out_img_addr_reg_729_pp0_iter4_reg <= out_img_addr_reg_729_pp0_iter3_reg;
        pix_4_reg_741 <= in_img_q0;
        sub_ln74_2_reg_751 <= sub_ln74_2_fu_436_p2;
        sub_ln74_reg_746 <= sub_ln74_fu_397_p2;
        tmp_7_reg_766 <= {{mag_fu_600_p2[11:8]}};
        trunc_ln85_reg_771 <= trunc_ln85_fu_616_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_storemerge_reg_175 <= ap_phi_reg_pp0_iter1_storemerge_reg_175;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_storemerge_reg_175 <= ap_phi_reg_pp0_iter2_storemerge_reg_175;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_storemerge_reg_175 <= ap_phi_reg_pp0_iter3_storemerge_reg_175;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln32_reg_689_pp0_iter1_reg == 1'd0))) begin
        gy_1_fu_72 <= p_0_0_04426_fu_96;
        p_0_0_04328_fu_100 <= pix_2_reg_734;
        p_0_0_04426_fu_96 <= pix_fu_365_p3;
        p_0_0_05130_fu_104 <= in_img_q0;
        pix_1_fu_76 <= p_0_0_04328_fu_100;
        pix_3_fu_80 <= p_0_0_05130_fu_104;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_205_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln32_reg_689_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 10'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 19'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 10'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_img_ce0 = 1'b1;
    end else begin
        in_img_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf_1_ce0 = 1'b1;
    end else begin
        linebuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_1_ce1 = 1'b1;
    end else begin
        linebuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln32_reg_689_pp0_iter1_reg == 1'd0))) begin
        linebuf_1_we0 = 1'b1;
    end else begin
        linebuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf_ce0 = 1'b1;
    end else begin
        linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_ce1 = 1'b1;
    end else begin
        linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln32_reg_689_pp0_iter1_reg == 1'd0))) begin
        linebuf_we0 = 1'b1;
    end else begin
        linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_img_ce0 = 1'b1;
    end else begin
        out_img_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_img_we0 = 1'b1;
    end else begin
        out_img_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_gx_fu_562_p3 = ((tmp_5_fu_548_p3[0:0] == 1'b1) ? sub_ln79_fu_556_p2 : empty_fu_529_p1);

assign abs_gy_fu_588_p3 = ((tmp_6_fu_574_p3[0:0] == 1'b1) ? sub_ln80_fu_582_p2 : gy_fu_538_p2);

assign add_ln32_1_fu_211_p2 = (ap_sig_allocacmp_indvar_flatten_load + 19'd1);

assign add_ln32_fu_223_p2 = (ap_sig_allocacmp_r_load + 10'd1);

assign add_ln34_fu_323_p2 = (select_ln32_fu_235_p3 + 10'd1);

assign add_ln49_fu_295_p2 = (tmp_1_fu_255_p3 + zext_ln49_fu_291_p1);

assign add_ln74_1_fu_450_p2 = (zext_ln74_1_fu_432_p1 + zext_ln73_5_fu_446_p1);

assign add_ln74_fu_515_p2 = ($signed(sub_ln74_2_reg_751) + $signed(sext_ln74_fu_509_p1));

assign add_ln75_fu_474_p2 = ($signed(sext_ln75_fu_470_p1) + $signed(zext_ln73_fu_381_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_186 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_175 = 'bx;

assign cmp5_fu_263_p2 = ((select_ln32_1_fu_243_p3 == 10'd0) ? 1'b1 : 1'b0);

assign empty_fu_529_p1 = gx_fu_523_p2[9:0];

assign gx_fu_523_p2 = (zext_ln74_2_fu_520_p1 + add_ln74_fu_515_p2);

assign gy_3_fu_533_p2 = (add_ln75_reg_761 - zext_ln73_4_fu_512_p1);

assign gy_fu_538_p2 = ($signed(gy_3_fu_533_p2) + $signed(sext_ln74_fu_509_p1));

assign icmp28_fu_279_p2 = ((tmp_3_fu_269_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_205_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 19'd262144) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_229_p2 = ((ap_sig_allocacmp_c_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_311_p2 = ((tmp_4_fu_301_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_620_p2 = (($signed(tmp_7_reg_766) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign in_img_address0 = zext_ln49_1_fu_344_p1;

assign linebuf_1_address1 = zext_ln34_fu_285_p1;

assign mag_fu_600_p2 = ($signed(sext_ln80_fu_596_p1) + $signed(zext_ln79_fu_570_p1));

assign or_ln62_fu_317_p2 = (icmp_ln62_fu_311_p2 | icmp28_fu_279_p2);

assign out_img_address0 = out_img_addr_reg_729_pp0_iter4_reg;

assign out_img_d0 = ap_phi_reg_pp0_iter5_storemerge_reg_175;

assign pix_2_fu_349_p3 = ((icmp28_reg_698[0:0] == 1'b1) ? 8'd0 : linebuf_1_q1);

assign pix_fu_365_p3 = ((cmp5_reg_693_pp0_iter1_reg[0:0] == 1'b1) ? 8'd0 : linebuf_q1);

assign select_ln32_1_fu_243_p3 = ((icmp_ln34_fu_229_p2[0:0] == 1'b1) ? add_ln32_fu_223_p2 : ap_sig_allocacmp_r_load);

assign select_ln32_fu_235_p3 = ((icmp_ln34_fu_229_p2[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_c_load);

assign select_ln85_fu_625_p3 = ((icmp_ln83_fu_620_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln85_reg_771);

assign sext_ln67_fu_544_p1 = gy_fu_538_p2;

assign sext_ln74_1_fu_421_p1 = $signed(sub_ln74_1_fu_415_p2);

assign sext_ln74_fu_509_p1 = $signed(sub_ln74_reg_746);

assign sext_ln75_fu_470_p1 = $signed(tmp_2_fu_462_p3);

assign sext_ln80_fu_596_p1 = $signed(abs_gy_fu_588_p3);

assign shl_ln74_1_fu_403_p3 = {{pix_1_fu_76}, {1'd0}};

assign shl_ln_fu_425_p3 = {{pix_2_reg_734}, {1'd0}};

assign sub_ln74_1_fu_415_p2 = (10'd0 - zext_ln74_fu_411_p1);

assign sub_ln74_2_fu_436_p2 = ($signed(sext_ln74_1_fu_421_p1) - $signed(zext_ln73_fu_381_p1));

assign sub_ln74_fu_397_p2 = (zext_ln73_2_fu_389_p1 - zext_ln73_3_fu_393_p1);

assign sub_ln79_fu_556_p2 = (10'd0 - empty_fu_529_p1);

assign sub_ln80_fu_582_p2 = ($signed(11'd0) - $signed(gy_fu_538_p2));

assign tmp_1_fu_255_p3 = {{trunc_ln49_fu_251_p1}, {9'd0}};

assign tmp_2_fu_462_p3 = {{tmp_fu_456_p2}, {1'd0}};

assign tmp_3_fu_269_p4 = {{select_ln32_1_fu_243_p3[9:1]}};

assign tmp_4_fu_301_p4 = {{select_ln32_fu_235_p3[9:1]}};

assign tmp_5_fu_548_p3 = gx_fu_523_p2[32'd10];

assign tmp_6_fu_574_p3 = sext_ln67_fu_544_p1[32'd31];

assign tmp_fu_456_p2 = (zext_ln73_1_fu_385_p1 - zext_ln68_fu_442_p1);

assign trunc_ln49_fu_251_p1 = select_ln32_1_fu_243_p3[8:0];

assign trunc_ln85_fu_616_p1 = mag_fu_600_p2[7:0];

assign zext_ln34_fu_285_p1 = select_ln32_fu_235_p3;

assign zext_ln49_1_fu_344_p1 = add_ln49_reg_703;

assign zext_ln49_fu_291_p1 = select_ln32_fu_235_p3;

assign zext_ln68_fu_442_p1 = p_0_0_05130_fu_104;

assign zext_ln73_1_fu_385_p1 = p_0_0_04426_fu_96;

assign zext_ln73_2_fu_389_p1 = pix_fu_365_p3;

assign zext_ln73_3_fu_393_p1 = pix_3_fu_80;

assign zext_ln73_4_fu_512_p1 = pix_4_reg_741;

assign zext_ln73_5_fu_446_p1 = in_img_q0;

assign zext_ln73_fu_381_p1 = gy_1_fu_72;

assign zext_ln74_1_fu_432_p1 = shl_ln_fu_425_p3;

assign zext_ln74_2_fu_520_p1 = add_ln74_1_reg_756;

assign zext_ln74_fu_411_p1 = shl_ln74_1_fu_403_p3;

assign zext_ln79_fu_570_p1 = abs_gx_fu_562_p3;

endmodule //sobel_accel_sobel_filter
