-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_accel_sobel_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_img_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    in_img_ce0 : OUT STD_LOGIC;
    in_img_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_img_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    out_img_ce0 : OUT STD_LOGIC;
    out_img_we0 : OUT STD_LOGIC;
    out_img_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of sobel_accel_sobel_filter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv19_40000 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln32_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln32_reg_689 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_689_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_689_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_689_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp5_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp5_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp5_reg_693_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp28_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp28_reg_698 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_295_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln49_reg_703 : STD_LOGIC_VECTOR (17 downto 0);
    signal linebuf_addr_reg_708 : STD_LOGIC_VECTOR (8 downto 0);
    signal linebuf_addr_reg_708_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal linebuf_1_addr_reg_714 : STD_LOGIC_VECTOR (8 downto 0);
    signal linebuf_1_addr_reg_714_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln62_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_reg_720 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_reg_720_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_reg_720_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_reg_720_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_img_addr_reg_729 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_img_addr_reg_729_pp0_iter2_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal out_img_addr_reg_729_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal out_img_addr_reg_729_pp0_iter4_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal pix_2_fu_349_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_2_reg_734 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_4_reg_741 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln74_fu_397_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln74_reg_746 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln74_2_fu_436_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln74_2_reg_751 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln74_1_fu_450_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln74_1_reg_756 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln75_fu_474_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln75_reg_761 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_reg_766 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln85_fu_616_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln85_reg_771 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln85_fu_625_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal linebuf_ce0 : STD_LOGIC;
    signal linebuf_we0 : STD_LOGIC;
    signal linebuf_ce1 : STD_LOGIC;
    signal linebuf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_1_ce0 : STD_LOGIC;
    signal linebuf_1_we0 : STD_LOGIC;
    signal linebuf_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal linebuf_1_ce1 : STD_LOGIC;
    signal linebuf_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter5_storemerge_reg_175 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln34_fu_285_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln49_1_fu_344_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal gy_1_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pix_1_fu_76 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pix_3_fu_80 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal c_fu_84 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln34_fu_323_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (9 downto 0);
    signal r_fu_88 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln32_1_fu_243_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_r_load : STD_LOGIC_VECTOR (9 downto 0);
    signal indvar_flatten_fu_92 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal add_ln32_1_fu_211_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0_0_04426_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pix_fu_365_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_04328_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_05130_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal icmp_ln34_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln32_fu_223_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln49_fu_251_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_269_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln32_fu_235_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_255_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln49_fu_291_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_4_fu_301_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln62_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln73_2_fu_389_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln73_3_fu_393_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln74_1_fu_403_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln74_fu_411_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln74_1_fu_415_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_425_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln74_1_fu_421_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln73_fu_381_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln74_1_fu_432_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_5_fu_446_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_1_fu_385_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln68_fu_442_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_456_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_462_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln75_fu_470_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln74_fu_509_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln74_2_fu_520_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln74_fu_515_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_523_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln73_4_fu_512_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_3_fu_533_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_538_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_529_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln79_fu_556_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal abs_gx_fu_562_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln67_fu_544_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_574_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln80_fu_582_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal abs_gy_fu_588_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln80_fu_596_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln79_fu_570_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mag_fu_600_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln83_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_186 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_accel_sobel_filter_linebuf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_accel_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    linebuf_U : component sobel_accel_sobel_filter_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_addr_reg_708_pp0_iter1_reg,
        ce0 => linebuf_ce0,
        we0 => linebuf_we0,
        d0 => pix_2_reg_734,
        address1 => linebuf_addr_reg_708,
        ce1 => linebuf_ce1,
        q1 => linebuf_q1);

    linebuf_1_U : component sobel_accel_sobel_filter_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_1_addr_reg_714_pp0_iter1_reg,
        ce0 => linebuf_1_ce0,
        we0 => linebuf_1_we0,
        d0 => in_img_q0,
        address1 => linebuf_1_address1,
        ce1 => linebuf_1_ce1,
        q1 => linebuf_1_q1);

    flow_control_loop_pipe_U : component sobel_accel_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_storemerge_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_186)) then
                if (((icmp_ln32_fu_205_p2 = ap_const_lv1_0) and (or_ln62_fu_317_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_storemerge_reg_175 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_storemerge_reg_175 <= ap_phi_reg_pp0_iter0_storemerge_reg_175;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter5_storemerge_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                if (((or_ln62_reg_720_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln32_reg_689_pp0_iter3_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter5_storemerge_reg_175 <= select_ln85_fu_625_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter5_storemerge_reg_175 <= ap_phi_reg_pp0_iter4_storemerge_reg_175;
                end if;
            end if; 
        end if;
    end process;

    c_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_186)) then
                if ((icmp_ln32_fu_205_p2 = ap_const_lv1_0)) then 
                    c_fu_84 <= add_ln34_fu_323_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_84 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_186)) then
                if ((icmp_ln32_fu_205_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_92 <= add_ln32_1_fu_211_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_92 <= ap_const_lv19_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_186)) then
                if ((icmp_ln32_fu_205_p2 = ap_const_lv1_0)) then 
                    r_fu_88 <= select_ln32_1_fu_243_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_88 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln49_reg_703 <= add_ln49_fu_295_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cmp5_reg_693 <= cmp5_fu_263_p2;
                cmp5_reg_693_pp0_iter1_reg <= cmp5_reg_693;
                icmp28_reg_698 <= icmp28_fu_279_p2;
                icmp_ln32_reg_689 <= icmp_ln32_fu_205_p2;
                icmp_ln32_reg_689_pp0_iter1_reg <= icmp_ln32_reg_689;
                linebuf_1_addr_reg_714 <= zext_ln34_fu_285_p1(9 - 1 downto 0);
                linebuf_1_addr_reg_714_pp0_iter1_reg <= linebuf_1_addr_reg_714;
                linebuf_addr_reg_708 <= zext_ln34_fu_285_p1(9 - 1 downto 0);
                linebuf_addr_reg_708_pp0_iter1_reg <= linebuf_addr_reg_708;
                or_ln62_reg_720 <= or_ln62_fu_317_p2;
                or_ln62_reg_720_pp0_iter1_reg <= or_ln62_reg_720;
                out_img_addr_reg_729 <= zext_ln49_1_fu_344_p1(18 - 1 downto 0);
                pix_2_reg_734 <= pix_2_fu_349_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln74_1_reg_756 <= add_ln74_1_fu_450_p2;
                add_ln75_reg_761 <= add_ln75_fu_474_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln32_reg_689_pp0_iter2_reg <= icmp_ln32_reg_689_pp0_iter1_reg;
                icmp_ln32_reg_689_pp0_iter3_reg <= icmp_ln32_reg_689_pp0_iter2_reg;
                or_ln62_reg_720_pp0_iter2_reg <= or_ln62_reg_720_pp0_iter1_reg;
                or_ln62_reg_720_pp0_iter3_reg <= or_ln62_reg_720_pp0_iter2_reg;
                out_img_addr_reg_729_pp0_iter2_reg <= out_img_addr_reg_729;
                out_img_addr_reg_729_pp0_iter3_reg <= out_img_addr_reg_729_pp0_iter2_reg;
                out_img_addr_reg_729_pp0_iter4_reg <= out_img_addr_reg_729_pp0_iter3_reg;
                pix_4_reg_741 <= in_img_q0;
                sub_ln74_2_reg_751 <= sub_ln74_2_fu_436_p2;
                sub_ln74_reg_746 <= sub_ln74_fu_397_p2;
                tmp_7_reg_766 <= mag_fu_600_p2(11 downto 8);
                trunc_ln85_reg_771 <= trunc_ln85_fu_616_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_storemerge_reg_175 <= ap_phi_reg_pp0_iter1_storemerge_reg_175;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_storemerge_reg_175 <= ap_phi_reg_pp0_iter2_storemerge_reg_175;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_storemerge_reg_175 <= ap_phi_reg_pp0_iter3_storemerge_reg_175;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln32_reg_689_pp0_iter1_reg = ap_const_lv1_0))) then
                gy_1_fu_72 <= p_0_0_04426_fu_96;
                p_0_0_04328_fu_100 <= pix_2_reg_734;
                p_0_0_04426_fu_96 <= pix_fu_365_p3;
                p_0_0_05130_fu_104 <= in_img_q0;
                pix_1_fu_76 <= p_0_0_04328_fu_100;
                pix_3_fu_80 <= p_0_0_05130_fu_104;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    abs_gx_fu_562_p3 <= 
        sub_ln79_fu_556_p2 when (tmp_5_fu_548_p3(0) = '1') else 
        empty_fu_529_p1;
    abs_gy_fu_588_p3 <= 
        sub_ln80_fu_582_p2 when (tmp_6_fu_574_p3(0) = '1') else 
        gy_fu_538_p2;
    add_ln32_1_fu_211_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv19_1));
    add_ln32_fu_223_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_load) + unsigned(ap_const_lv10_1));
    add_ln34_fu_323_p2 <= std_logic_vector(unsigned(select_ln32_fu_235_p3) + unsigned(ap_const_lv10_1));
    add_ln49_fu_295_p2 <= std_logic_vector(unsigned(tmp_1_fu_255_p3) + unsigned(zext_ln49_fu_291_p1));
    add_ln74_1_fu_450_p2 <= std_logic_vector(unsigned(zext_ln74_1_fu_432_p1) + unsigned(zext_ln73_5_fu_446_p1));
    add_ln74_fu_515_p2 <= std_logic_vector(unsigned(sub_ln74_2_reg_751) + unsigned(sext_ln74_fu_509_p1));
    add_ln75_fu_474_p2 <= std_logic_vector(signed(sext_ln75_fu_470_p1) + signed(zext_ln73_fu_381_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_186_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_186 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln32_fu_205_p2, ap_start_int)
    begin
        if (((icmp_ln32_fu_205_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln32_reg_689_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln32_reg_689_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_phi_reg_pp0_iter0_storemerge_reg_175 <= "XXXXXXXX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_84, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_92, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv19_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_r_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, r_fu_88, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_r_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_r_load <= r_fu_88;
        end if; 
    end process;

    cmp5_fu_263_p2 <= "1" when (select_ln32_1_fu_243_p3 = ap_const_lv10_0) else "0";
    empty_fu_529_p1 <= gx_fu_523_p2(10 - 1 downto 0);
    gx_fu_523_p2 <= std_logic_vector(unsigned(zext_ln74_2_fu_520_p1) + unsigned(add_ln74_fu_515_p2));
    gy_3_fu_533_p2 <= std_logic_vector(unsigned(add_ln75_reg_761) - unsigned(zext_ln73_4_fu_512_p1));
    gy_fu_538_p2 <= std_logic_vector(unsigned(gy_3_fu_533_p2) + unsigned(sext_ln74_fu_509_p1));
    icmp28_fu_279_p2 <= "1" when (tmp_3_fu_269_p4 = ap_const_lv9_0) else "0";
    icmp_ln32_fu_205_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv19_40000) else "0";
    icmp_ln34_fu_229_p2 <= "1" when (ap_sig_allocacmp_c_load = ap_const_lv10_200) else "0";
    icmp_ln62_fu_311_p2 <= "1" when (tmp_4_fu_301_p4 = ap_const_lv9_0) else "0";
    icmp_ln83_fu_620_p2 <= "1" when (signed(tmp_7_reg_766) > signed(ap_const_lv4_0)) else "0";
    in_img_address0 <= zext_ln49_1_fu_344_p1(18 - 1 downto 0);

    in_img_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_img_ce0 <= ap_const_logic_1;
        else 
            in_img_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_1_address1 <= zext_ln34_fu_285_p1(9 - 1 downto 0);

    linebuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_1_ce0 <= ap_const_logic_1;
        else 
            linebuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_1_ce1 <= ap_const_logic_1;
        else 
            linebuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln32_reg_689_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln32_reg_689_pp0_iter1_reg = ap_const_lv1_0))) then 
            linebuf_1_we0 <= ap_const_logic_1;
        else 
            linebuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_ce0 <= ap_const_logic_1;
        else 
            linebuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_ce1 <= ap_const_logic_1;
        else 
            linebuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln32_reg_689_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln32_reg_689_pp0_iter1_reg = ap_const_lv1_0))) then 
            linebuf_we0 <= ap_const_logic_1;
        else 
            linebuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mag_fu_600_p2 <= std_logic_vector(signed(sext_ln80_fu_596_p1) + signed(zext_ln79_fu_570_p1));
    or_ln62_fu_317_p2 <= (icmp_ln62_fu_311_p2 or icmp28_fu_279_p2);
    out_img_address0 <= out_img_addr_reg_729_pp0_iter4_reg;

    out_img_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_img_ce0 <= ap_const_logic_1;
        else 
            out_img_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_img_d0 <= ap_phi_reg_pp0_iter5_storemerge_reg_175;

    out_img_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_img_we0 <= ap_const_logic_1;
        else 
            out_img_we0 <= ap_const_logic_0;
        end if; 
    end process;

    pix_2_fu_349_p3 <= 
        ap_const_lv8_0 when (icmp28_reg_698(0) = '1') else 
        linebuf_1_q1;
    pix_fu_365_p3 <= 
        ap_const_lv8_0 when (cmp5_reg_693_pp0_iter1_reg(0) = '1') else 
        linebuf_q1;
    select_ln32_1_fu_243_p3 <= 
        add_ln32_fu_223_p2 when (icmp_ln34_fu_229_p2(0) = '1') else 
        ap_sig_allocacmp_r_load;
    select_ln32_fu_235_p3 <= 
        ap_const_lv10_0 when (icmp_ln34_fu_229_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln85_fu_625_p3 <= 
        ap_const_lv8_FF when (icmp_ln83_fu_620_p2(0) = '1') else 
        trunc_ln85_reg_771;
        sext_ln67_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_fu_538_p2),32));

        sext_ln74_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln74_1_fu_415_p2),11));

        sext_ln74_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln74_reg_746),11));

        sext_ln75_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_462_p3),11));

        sext_ln80_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_gy_fu_588_p3),12));

    shl_ln74_1_fu_403_p3 <= (pix_1_fu_76 & ap_const_lv1_0);
    shl_ln_fu_425_p3 <= (pix_2_reg_734 & ap_const_lv1_0);
    sub_ln74_1_fu_415_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(zext_ln74_fu_411_p1));
    sub_ln74_2_fu_436_p2 <= std_logic_vector(signed(sext_ln74_1_fu_421_p1) - signed(zext_ln73_fu_381_p1));
    sub_ln74_fu_397_p2 <= std_logic_vector(unsigned(zext_ln73_2_fu_389_p1) - unsigned(zext_ln73_3_fu_393_p1));
    sub_ln79_fu_556_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(empty_fu_529_p1));
    sub_ln80_fu_582_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gy_fu_538_p2));
    tmp_1_fu_255_p3 <= (trunc_ln49_fu_251_p1 & ap_const_lv9_0);
    tmp_2_fu_462_p3 <= (tmp_fu_456_p2 & ap_const_lv1_0);
    tmp_3_fu_269_p4 <= select_ln32_1_fu_243_p3(9 downto 1);
    tmp_4_fu_301_p4 <= select_ln32_fu_235_p3(9 downto 1);
    tmp_5_fu_548_p3 <= gx_fu_523_p2(10 downto 10);
    tmp_6_fu_574_p3 <= sext_ln67_fu_544_p1(31 downto 31);
    tmp_fu_456_p2 <= std_logic_vector(unsigned(zext_ln73_1_fu_385_p1) - unsigned(zext_ln68_fu_442_p1));
    trunc_ln49_fu_251_p1 <= select_ln32_1_fu_243_p3(9 - 1 downto 0);
    trunc_ln85_fu_616_p1 <= mag_fu_600_p2(8 - 1 downto 0);
    zext_ln34_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln32_fu_235_p3),64));
    zext_ln49_1_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_reg_703),64));
    zext_ln49_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln32_fu_235_p3),18));
    zext_ln68_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_05130_fu_104),9));
    zext_ln73_1_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_04426_fu_96),9));
    zext_ln73_2_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pix_fu_365_p3),9));
    zext_ln73_3_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pix_3_fu_80),9));
    zext_ln73_4_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pix_4_reg_741),11));
    zext_ln73_5_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_img_q0),10));
    zext_ln73_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gy_1_fu_72),11));
    zext_ln74_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_425_p3),10));
    zext_ln74_2_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_1_reg_756),11));
    zext_ln74_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln74_1_fu_403_p3),10));
    zext_ln79_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(abs_gx_fu_562_p3),12));
end behav;
